version: 2

jobs:
  
  build:
    docker:
      - image: circleci/node:carbon
    steps:
      - checkout
      - run: npm install -g npm@latest
      - run: npm ci
      - run: npm run build
      - run: npm run deploy
        