version: 2

jobs:
  
  build:
    docker:
      - image: circleci/node:carbon
    steps:
      - add_ssh_keys:
          fingerprints:
            - "b3:e5:21:46:a7:8a:04:55:6b:d9:47:3b:e3:1d:07:bf"
      - checkout
      - run: npm install
      - run: npm run build
      - run: npm run deploy
        